"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 05:01:08.768398
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_project_id'), ['project_id'], unique=False)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('users',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('projects',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_question', sa.Text(), nullable=False),
    sa.Column('decision_to_inform', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_projects_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)

    op.create_table('approvals',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=80), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_approvals_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_project_id'), ['project_id'], unique=False)

    op.create_table('constructs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('library_key', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('measurement', sa.String(length=20), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_constructs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constructs')),
    sa.UniqueConstraint('project_id', 'code', name=op.f('uq_constructs_project_id'))
    )
    with op.batch_alter_table('constructs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constructs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_constructs_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('datasets',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_datasets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)

    op.create_table('experiments',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('primary_metric', sa.String(length=200), nullable=False),
    sa.Column('baseline_rate', sa.Float(), nullable=False),
    sa.Column('mde', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('sample_size_per_arm', sa.Integer(), nullable=False),
    sa.Column('expected_daily_traffic', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_experiments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('hypotheses',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('iv', sa.String(length=100), nullable=False),
    sa.Column('dv', sa.String(length=100), nullable=False),
    sa.Column('mediator', sa.String(length=100), nullable=False),
    sa.Column('moderator', sa.String(length=100), nullable=False),
    sa.Column('expected_direction', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verdict_rationale', sa.Text(), nullable=False),
    sa.Column('verdict_evidence', sa.JSON(), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_hypotheses_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses')),
    sa.UniqueConstraint('project_id', 'code', name=op.f('uq_hypotheses_project_id'))
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hypotheses_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('insights',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('implication', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('uncertainty', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_model_generated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_insights_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights')),
    sa.UniqueConstraint('project_id', 'seq', name=op.f('uq_insights_project_id'))
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('journeys',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template', sa.String(length=40), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('voc', sa.JSON(), nullable=False),
    sa.Column('voc_dataset_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_journeys_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journeys'))
    )
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journeys_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journeys_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_members'))
    )
    op.create_table('recommendations',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_model_generated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_recommendations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('project_id', 'seq', name=op.f('uq_recommendations_project_id'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('reports',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('is_model_generated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('finalized_by', sa.String(length=36), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('research_plans',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_research_plans_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_plans'))
    )
    with op.batch_alter_table('research_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_plans_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_plans_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('research_questions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_research_questions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_questions')),
    sa.UniqueConstraint('project_id', 'code', name=op.f('uq_research_questions_project_id'))
    )
    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_questions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_questions_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('baseline_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('model', sa.JSON(), nullable=False),
    sa.Column('levers', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['scenarios.id'], name=op.f('fk_scenarios_baseline_id_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenarios_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_baseline_id'), ['baseline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('surveys',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_surveys_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys'))
    )
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surveys_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_surveys_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('workflow', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workflow_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_project_id'), ['project_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=True),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_by', sa.String(length=36), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_agent_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_agent_runs_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_cols', sa.Integer(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('operations', sa.JSON(), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_versions_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_dataset_versions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions')),
    sa.UniqueConstraint('dataset_id', 'version', name=op.f('uq_dataset_versions_dataset_id'))
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('decisions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_decisions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_decisions_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_project_id'), ['project_id'], unique=False)

    op.create_table('pain_points',
    sa.Column('journey_id', sa.String(length=36), nullable=False),
    sa.Column('stage_key', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('reach', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('quotes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_pain_points_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pain_points'))
    )
    with op.batch_alter_table('pain_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pain_points_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pain_points_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('questions',
    sa.Column('survey_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_id', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('scale', sa.JSON(), nullable=False),
    sa.Column('logic', sa.JSON(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('construct_code', sa.String(length=20), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_questions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_questions_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source_run_id'), ['source_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_survey_id'), ['survey_id'], unique=False)

    op.create_table('touchpoints',
    sa.Column('journey_id', sa.String(length=36), nullable=False),
    sa.Column('stage_key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_touchpoints_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_touchpoints'))
    )
    with op.batch_alter_table('touchpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_touchpoints_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_touchpoints_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('variables',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('construct_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('var_type', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('scale_min', sa.Float(), nullable=True),
    sa.Column('scale_max', sa.Float(), nullable=True),
    sa.Column('value_labels', sa.JSON(), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], name=op.f('fk_variables_construct_id_constructs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_variables_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variables')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_variables_project_id'))
    )
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variables_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_variables_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('analyses',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_analyses_dataset_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_analyses_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('interventions',
    sa.Column('journey_id', sa.String(length=36), nullable=False),
    sa.Column('pain_point_id', sa.String(length=36), nullable=True),
    sa.Column('stage_key', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('uplift_low', sa.Float(), nullable=False),
    sa.Column('uplift_mid', sa.Float(), nullable=False),
    sa.Column('uplift_high', sa.Float(), nullable=False),
    sa.Column('effort', sa.String(length=2), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('simulation', sa.JSON(), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_interventions_journey_id_journeys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pain_point_id'], ['pain_points.id'], name=op.f('fk_interventions_pain_point_id_pain_points'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions'))
    )
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interventions_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('evidence',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=True),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('design', sa.String(length=40), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('effect_label', sa.String(length=50), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('ci_low', sa.Float(), nullable=True),
    sa.Column('ci_high', sa.Float(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_evidence_analysis_id_analyses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_evidence_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('project_id', 'seq', name=op.f('uq_evidence_project_id'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('segments',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('share', sa.Float(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('persona', sa.JSON(), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_segments_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_segments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segments'))
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_source_run_id'), ['source_run_id'], unique=False)

    op.create_table('insight_evidence',
    sa.Column('insight_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_insight_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_insight_evidence_insight_id_insights'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insight_id', 'evidence_id', name=op.f('pk_insight_evidence'))
    )
    op.create_table('recommendation_evidence',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_recommendation_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_evidence_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id', 'evidence_id', name=op.f('pk_recommendation_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_evidence')
    op.drop_table('insight_evidence')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_segments_project_id'))
        batch_op.drop_index(batch_op.f('ix_segments_analysis_id'))

    op.drop_table('segments')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_project_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_analysis_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interventions_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_interventions_journey_id'))

    op.drop_table('interventions')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_project_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_dataset_version_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variables_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_variables_project_id'))

    op.drop_table('variables')
    with op.batch_alter_table('touchpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_touchpoints_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_touchpoints_journey_id'))

    op.drop_table('touchpoints')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_survey_id'))
        batch_op.drop_index(batch_op.f('ix_questions_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_questions_project_id'))

    op.drop_table('questions')
    with op.batch_alter_table('pain_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pain_points_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_pain_points_journey_id'))

    op.drop_table('pain_points')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_project_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_id'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_project_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_project_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveys_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_surveys_project_id'))

    op.drop_table('surveys')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_project_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_baseline_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_questions_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_research_questions_project_id'))

    op.drop_table('research_questions')
    with op.batch_alter_table('research_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_plans_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_research_plans_project_id'))

    op.drop_table('research_plans')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_reports_project_id'))

    op.drop_table('reports')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_project_id'))

    op.drop_table('recommendations')
    op.drop_table('project_members')
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journeys_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_journeys_project_id'))

    op.drop_table('journeys')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insights_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_insights_project_id'))

    op.drop_table('insights')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_hypotheses_project_id'))

    op.drop_table('hypotheses')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_project_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('constructs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constructs_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_constructs_project_id'))

    op.drop_table('constructs')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_project_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('organizations')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
