"""One-click Lake Toba demo: runs the whole closed loop on SYNTHETIC data through the real agents.

Only the design adoption and the cleaning plan are approved automatically (recorded in the audit log as demo
approvals) so the pipeline can finish. Insights, verdicts, recommendations, the strategy decision and the
experiments stay pending so the person experiences the human approval gates.
"""

from __future__ import annotations

import logging
import threading
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session

from .. import audit
from ..config import get_settings
from ..db import session_factory
from ..models import Approval, Project, ProjectMember, WorkflowRun
from . import approval_handlers  # noqa: F401  (register handlers)
from . import approvals
from . import datasets as dataset_service

logger = logging.getLogger("mdos.demo")

DEMO_QUESTION = "I want to know whether tourists would pay Rp 150,000 for a new Lake Toba cultural experience."
DEMO_CONTEXT = ("A half-day cultural experience in a Batak village on Samosir Island: welcome with local storytelling, "
                "a tortor dance performance, hands-on ulos weaving and a traditional snack. Target launch: next high season.")


def demo_file(name: str) -> Path:
    packaged = Path(__file__).resolve().parents[1] / "demo_data" / name
    if packaged.exists():
        return packaged
    return Path(__file__).resolve().parents[3] / "samples" / name


def create_demo_project(db: Session, user_id: str, org_id: str) -> Project:
    project = Project(org_id=org_id, name="Lake Toba cultural experience (demo)", business_question=DEMO_QUESTION,
                      decision_to_inform="Whether to launch the experience, at what price, and how to design the visitor journey.",
                      context=DEMO_CONTEXT, industry="tourism", geography="Indonesia", currency="IDR", is_demo=True,
                      brief={"demo_status": "building"}, created_by=user_id)
    db.add(project)
    db.flush()
    db.add(ProjectMember(project_id=project.id, user_id=user_id, role="owner"))
    audit.record(db, org_id=org_id, project_id=project.id, actor_type="user", actor_id=user_id, action="demo.create",
                 entity_type="project", entity_id=project.id)
    db.commit()
    if get_settings().execution_mode == "sync":
        seed(project.id, user_id)
    else:
        threading.Thread(target=seed, args=(project.id, user_id), daemon=True, name="mdos-demo").start()
    return project


def _approve(db: Session, project: Project, action: str, user_id: str) -> dict:
    pending = db.scalars(select(Approval).where(Approval.project_id == project.id, Approval.action == action,
                                                Approval.status == "pending")).all()
    outcome = {}
    for a in pending:
        outcome = approvals.decide(db, project, a, "approved", user_id, "Demo project: approved automatically while loading the demo")
    db.commit()
    return outcome


def _upload(db: Session, project: Project, filename: str, kind: str, user_id: str):
    path = demo_file(filename)
    df, fmt = dataset_service.parse_upload(filename, path.read_bytes())
    dataset = dataset_service.create_dataset(db, project, name=f"{filename} (synthetic)", kind=kind, origin="synthetic_demo",
                                             filename=filename, df=df, fmt=fmt, user_id=user_id,
                                             description="Synthetic demonstration data generated by MDOS. Not real respondents.")
    db.commit()
    return dataset


def seed(project_id: str, user_id: str) -> None:
    from ..agents import supervisor

    db = session_factory()()
    try:
        project = db.get(Project, project_id)

        def run(workflow: str, inputs: dict | None = None) -> WorkflowRun:
            wf = WorkflowRun(project_id=project.id, workflow=workflow, status="queued", input=inputs or {},
                             steps=supervisor.WORKFLOWS[workflow]["steps"], current_step=0,
                             context={**supervisor.WORKFLOWS[workflow]["state"], **(inputs or {})}, created_by=user_id)
            db.add(wf)
            db.commit()
            supervisor.execute(wf.id)
            db.expire_all()
            return db.get(WorkflowRun, wf.id)

        design = run("research_design")
        _approve(db, project, "adopt_design", user_id)
        survey = _upload(db, project, "lake_toba_survey.csv", "survey", user_id)
        analysis = run("research_analysis", {"dataset_id": survey.id})
        if analysis.status == "awaiting_approval":
            _approve(db, project, "apply_cleaning", user_id)
            analysis = db.get(WorkflowRun, analysis.id)
            analysis.status = "queued"
            db.commit()
            supervisor.execute(analysis.id)
        run("strategy_baseline")
        reviews = _upload(db, project, "lake_toba_reviews.csv", "reviews", user_id)
        run("journey_voc", {"reviews_dataset_id": reviews.id, "text_column": "review_text", "rating_column": "rating",
                            "journey_name": "Lake Toba visitor journey"})
        db.expire_all()
        project = db.get(Project, project_id)
        project.brief = {**(project.brief or {}), "demo_status": "ready", "design_run": design.id}
        db.commit()
    except Exception as exc:  # noqa: BLE001 - report demo failures on the project instead of crashing a thread
        logger.exception("Demo seeding failed")
        db.rollback()
        project = db.get(Project, project_id)
        if project:
            project.brief = {**(project.brief or {}), "demo_status": "failed", "demo_error": str(exc)[:500]}
            db.commit()
    finally:
        db.close()
